-- MySQL Script generated by MySQL Workbench
-- Sun Mar 19 18:47:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AirBnB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AirBnB` ;

-- -----------------------------------------------------
-- Schema AirBnB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AirBnB` DEFAULT CHARACTER SET utf8 ;
USE `AirBnB` ;

-- -----------------------------------------------------
-- Table `AirBnB`.`proprietaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AirBnB`.`proprietaire` ;

CREATE TABLE IF NOT EXISTS `AirBnB`.`proprietaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telephone` INT(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirBnB`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AirBnB`.`adresse` ;

CREATE TABLE IF NOT EXISTS `AirBnB`.`adresse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numerorue` INT NOT NULL,
  `rue` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `codepostal` INT(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirBnB`.`logement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AirBnB`.`logement` ;

CREATE TABLE IF NOT EXISTS `AirBnB`.`logement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NOT NULL,
  `proprietaire_id` INT NOT NULL,
  `adresse_id` INT NOT NULL,
  PRIMARY KEY (`id`, `proprietaire_id`, `adresse_id`),
  CONSTRAINT `fk_logement_proprietaire`
    FOREIGN KEY (`proprietaire_id`)
    REFERENCES `AirBnB`.`proprietaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logement_adresse1`
    FOREIGN KEY (`adresse_id`)
    REFERENCES `AirBnB`.`adresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_logement_proprietaire_idx` ON `AirBnB`.`logement` (`proprietaire_id` ASC);

CREATE INDEX `fk_logement_adresse1_idx` ON `AirBnB`.`logement` (`adresse_id` ASC);


-- -----------------------------------------------------
-- Table `AirBnB`.`planning`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AirBnB`.`planning` ;

CREATE TABLE IF NOT EXISTS `AirBnB`.`planning` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datedebut` DATE NOT NULL,
  `datefin` DATE NOT NULL,
  `logement_id` INT NOT NULL,
  PRIMARY KEY (`id`, `logement_id`),
  CONSTRAINT `fk_planning_logement1`
    FOREIGN KEY (`logement_id`)
    REFERENCES `AirBnB`.`logement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_planning_logement1_idx` ON `AirBnB`.`planning` (`logement_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
